### ISSUE TITLE
Unable to install using Laravel 11

### ISSUE THREAD

**Issue by ahinkle** [stefanzweifel/sidecar-browsershot#119]
Thanks for the new release on Laravel 11. I'm seeing the following issue when trying to upgrade to 2.3.0:

```
wnx/sidecar-browsershot v2.3.0 requires hammerstone/sidecar ^0.4.0 -> satisfiable by hammerstone/sidecar[v0.4.0, v0.4.1, v0.4.2].

hammerstone/sidecar[v0.4.0, ..., v0.4.2] require illuminate/support ^8.0|^9.0|^10 -> found illuminate/support[v8.0.0, ..., 8.x-dev, v9.0.0-beta.1, ..., 9.x-dev, v10.0.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require.
```

I thought `^0.4.0` would be supportive of Sidecar `v0.5.0` but maybe I'm mistaken. Any ideas here?

Thanks so much!

**Comment by stefanzweifel** [comment]
Noticed that Aaron released Laravel 11 support this morning in the gym and hit _release_ in this package without verify that it actuall works. 🤦

I also noticed that I'm unable to install `hammerstone/sidecar` in a fresh Laravel 11 app as well. 🤔

**Comment by stefanzweifel** [comment]
Thanks for the PR again.
The test suite on GitHub Actions still [fails](https://github.com/stefanzweifel/sidecar-browsershot/actions/runs/8377087186/job/22938342749), but that is a _me_ issue. :)

Will tag a hotfix release shorty. Please, feel free to (re)open issues if you run into problems.
