### ISSUE TITLE
Add sidecar v0.6 to the list of allowed versions (right now it just has 4 and 5).

### ISSUE THREAD

**Issue by TomestoneGG** [stefanzweifel/sidecar-browsershot#131]
Add sidecar v0.6 to the list of allowed versions (right now it just has 4 and 5).

**Comment by lionslair** [comment]
Yeah he made another that is v6

https://github.com/hammerstonedev/sidecar/releases

**Comment by stefanzweifel** [comment]
This has been fixed in #132 and has been released in https://github.com/stefanzweifel/sidecar-browsershot/releases/tag/v2.3.2.
