### ISSUE TITLE
No space left on device

### ISSUE THREAD

**Issue by phuclh** [stefanzweifel/sidecar-browsershot#30]
I notice that this error will occur when I run with high concurrency (many browser instances). Does the tmp data from the puppeteer is saved in `/tmp`. If it does then weird because the `tmp` folder can allow 10GB.

This is the error I got:

```
Hammerstone\Sidecar\Exceptions\LambdaExecutionException
Lambda Execution Exception for Wnx\SidecarBrowsershot\Functions\BrowsershotFunction: "Command failed: node ./browser.js '-f file:///tmp/browsershot.js'
[Error: ENOSPC: no space left on device, mkdtemp '/tmp/puppeteer_dev_chrome_profile-1WPNyY'] {
  errno: -28,
  code: 'ENOSPC',
  syscall: 'mkdtemp',
  path: '/tmp/puppeteer_dev_chrome_profile-1WPNyY'
}
. [TRACE] Error: Command failed: node ./browser.js '-f file:///tmp/browsershot.js' [Error: ENOSPC: no space left on device, mkdtemp '/tmp/puppeteer_dev_chrome_profile-1WPNyY'] { errno: -28,".
```

Another exception I got is about: `Error: net::ERR_INSUFFICIENT_RESOURCES `

```
Hammerstone\Sidecar\Exceptions\LambdaExecutionException
Lambda Execution Exception for Wnx\SidecarBrowsershot\Functions\BrowsershotFunction: "Command failed: node ./browser.js '-f file:///tmp/browsershot.js'
Error: net::ERR_INSUFFICIENT_RESOURCES at https://var.recreplanet.fr/rollergliss-la-garde-piste-roller-famille-patin-roulette-83
    at navigate (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:164:23)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async FrameManager.navigateFrame (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:141:21)
    at async Frame.goto (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:541:16)
    at async Page.goto (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/Page.js:1200:16)
    at async callChrome (/var/task/browser.js:251:26)
. [TRACE] Error: Command failed: node ./browser.js '-f file:///tmp/browsershot.js' Error: net::ERR_INSUFFICIENT_RESOURCES at https://var.recreplanet.fr/rollergliss-la-garde-piste-roller-famille-patin-roulette-83 at navigate (/opt/nodejs/node_modules/puppeteer-core/lib/cjs/puppeteer/common/FrameManager.js:164:23)".
```

I read this https://github.com/mifi/reactive-video/issues/11 and seems this exception is also about the disk space or memory. I tried to increase the memory of the lambda function to see if this exception come back or not. I will report later.

**Comment by phuclh** [comment]
> Sorry for my late reply here.
> 
> Initially I didn't really understood the issue here. I am/was no Lambda expert. But now, after a year of running this in my own apps, I run into the same issue. It seems we need to manually clean up the `/tmp/puppeteer_dev_chrome_profile-*` folders, after the browser has generated the screenshot.
> 
> Will try to tackle this issue in the next couple of days. Upgrading the ephermal storage isn't a good solution and just costs money.

This issue is related to the `tmp` folder storage. I increased it and everything is good now!

**Comment by Francismori7** [comment]
I'm getting the issue this morning, it seems like the fix hasn't worked for me, is there a way I can manually clear the files in case they are remnants?

`Hammerstone\Sidecar\Exceptions\LambdaExecutionException: Lambda Execution Exception for Wnx\SidecarBrowsershot\Functions\BrowsershotFunction: "ENOSPC: no space left on device, write. [TRACE] Error: ENOSPC: no space left on device, write at Object.writeSync (node:fs:929:3) at Object.writeFileSync (node:fs:2328:26)". in /var/www/intranet.grouperatte.com/vendor/hammerstone/sidecar/src/Results/SettledResult.php:103`

**Comment by Francismori7** [comment]
@stefanzweifel I'm actually getting another weird error now instead... I'll post a new issue.
