### ISSUE TITLE
encoding differs

### ISSUE THREAD

**Issue by Silver343** [stefanzweifel/sidecar-browsershot#34]
I am creating a base64pdf and passing it to Spatie's media library, it fails as decoding and reencoding do not match, it works when running browserShot locally.

it seems that the encode pdf returned uses a different encoder.

Sorry there's not much detail.

**Comment by stefanzweifel** [comment]
Thanks for reporting.
Could you at least share some code examples, what you're trying to do?

That would help me enormously as I then don't have to spend time recreating a code example from a single sentence.

**Comment by Silver343** [comment]
Hi,

I have created a [repo](https://github.com/Silver343/BrowsershotBase64) with a failing test.

I am trying to create a base64 version of a pdf 

`$pdf = SidecarBrowsershot::html($content)
            ->margins(10, 18, 18, 10)
            ->format('A4')
            ->scale(0.8)
            ->showBackground()
            ->base64pdf();`

and then pass it to Spatie's media Library.

`$this->invoice->addMediaFromBase64($pdf,'application/pdf')->usingFileName($this->invoice->number.'.pdf')->toMediaCollection('invoices');`

The issue occurs as the AddMediaFromBase64 method reencodes the base64 pdf `if (base64_encode($binaryData) !== $base64data) {
            throw InvalidBase64Data::create();
        }` this fails, which seems to indicate that the pdf is encoded differently in lambda.

Many thanks for your help.

**Comment by Silver343** [comment]
@levisudak thanks this worked, I'll submit a PR.

**Comment by stefanzweifel** [comment]
Thanks for the PR @Silver343. 
A new version has been tagged with this fix: https://github.com/stefanzweifel/sidecar-browsershot/releases/tag/v1.4.1.
