### ISSUE TITLE
Emoji CDN sometimes return 429

### ISSUE THREAD

**Issue by Admiral-Enigma** [stefanzweifel/sidecar-browsershot#50]
This line sometimes fail because the CDN returns a 429 Too many request.
`await chromium.font('https://raw.githack.com/googlei18n/noto-emoji/master/fonts/NotoColorEmoji.ttf');`

Is there some way to change this url in a config, so that we can self host the font? Or maybe the package needs to use a different CDN.

Is there any benefit from loading the font file during cold boot rather than just including it in the lambda bundle?

**Comment by Admiral-Enigma** [comment]
Yeah, I'm leaning more to the side of including the font file directly in the bundle as it removes the network call and makes the cold boot faster in theory. The bundle size is already kinda big because it's loading the chromium layer thing, so I don't think an extra 13 MB makes that big of a difference.

**Comment by Admiral-Enigma** [comment]
@stefanzweifel I could make a PR for this later today if thats okay?

**Comment by stefanzweifel** [comment]
@Admiral-Enigma Sure, feel free to send a PR for this.

**Comment by stefanzweifel** [comment]
This issue has been resolved in #51 and in [v1.6.2](https://github.com/stefanzweifel/sidecar-browsershot/releases/tag/v1.6.2).

**Comment by Admiral-Enigma** [comment]
Hey @stefanzweifel 
Just wanted to let you know, since the update we have not had a single browsershot lambda fail in production! 🥳

Thank you for the help with the PR and for maintaining this project!

**Comment by stefanzweifel** [comment]
@Admiral-Enigma Great to hear! I also redeployed the lambda in my production app and also didn't see any errors at all anymore.

I had to revert to your solution in a recent release and we now bundle the font in the packge (FYI).
