### ISSUE TITLE
Invoke Error 429

### ISSUE THREAD

**Issue by ScottSmudger** [stefanzweifel/sidecar-browsershot#53]
Hi there,

We seem to be receiving error 429 exceptions semi-frequently from our browsershot lambda function.

There are no throttle metrics from the function, however from the cloudwatch logs we receive:

```
Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "Unexpected status code: 429.",
    "stack": [
        "Error: Unexpected status code: 429.",
        "    at intoError (/var/runtime/Errors.js:27:12)",
        "    at postError (/var/runtime/CallbackContext.js:21:47)",
        "    at done (/var/runtime/CallbackContext.js:59:7)",
        "    at fail (/var/runtime/CallbackContext.js:71:7)",
        "    at /var/runtime/CallbackContext.js:113:16",
        "    at processTicksAndRejections (internal/process/task_queues.js:95:5)"
    ]
}
```

chrome-aws-lambda layer is arn:aws:lambda:eu-west-2:764866452798:layer:chrome-aws-lambda:31 on NodeJS 14.x

Thanks,
Scott

**Comment by ScottSmudger** [comment]
Actually I have just seen #50 so I'm going to try that first!

**Comment by stefanzweifel** [comment]
Yeah, this seems to be happening as the font to render Emojis hits a rate limit. Let me know, if updating the package to the latest version doesn't not resolve the issue.
