### ISSUE TITLE
file_put_contents(/var/task/vendor/wnx/sidecar-browsershot/src/Functions/../../resources/lambda/NotoColorEmoji.ttf): Failed to open stream: Read-only file system

### ISSUE THREAD

**Issue by phuclh** [stefanzweifel/sidecar-browsershot#55]
After upgrading to the latest version, I cannot run `sidecar:deploy --activate` on Laravel Vapor anymore.

This is the error: `file_put_contents(/var/task/vendor/wnx/sidecar-browsershot/src/Functions/../../resources/lambda/NotoColorEmoji.ttf): Failed to open stream: Read-only file system`

**Comment by stefanzweifel** [comment]
Haven't used Laravel Vapor before, but I assume the code to download the font to a local filesystem fails. As Vapor is AWS Lambda, there is no permanent filesystem.

Then it seems we have to bundle the font in the package itself and keep it up to to date. Will fix this in the coming hours.

Thanks for reporting and sorry for the trouble this caused.

**Comment by phuclh** [comment]
> Haven't used Laravel Vapor before, but I assume the code to download the font to a local filesystem fails. As Vapor is AWS Lambda, there is no permanent filesystem.
> 
> Then it seems we have to bundle the font in the package itself and keep it up to to date. Will fix this in the coming hours.
> 
> Thanks for reporting and sorry for the trouble this caused.

No worries, thank you so much for the quick response :D

**Comment by stefanzweifel** [comment]
I've just tagged [v1.6.3](https://github.com/stefanzweifel/sidecar-browsershot/releases/tag/v1.6.3) that resolves this issue. The font is now bundled in the package.
