### ISSUE TITLE
Loading never stop

### ISSUE THREAD

**Issue by luxorwannabe** [stefanzweifel/sidecar-browsershot#76]
### Discussed in https://github.com/stefanzweifel/sidecar-browsershot/discussions/75

<div type='discussions-op-text'>

<sup>Originally posted by **luxorwannabe** June 21, 2023</sup>
Hi, first of all thank you for **sidecar-browsershot.**..

I have successfully installed it and have it connected to S3 Buckets, I found one zip with random name there, also I can see the **sc-lamdabrowsershot-production-browsershot** function listed in Lamba Functions.
But when I try to run it the browser keeps loading never stop (almost 5 minutes) and ends up with the 503 timeout gateway...

Can you help me with this? Thanks</div>

**Comment by stefanzweifel** [comment]
Hi there, I'm closing this issue, as you already opened as discussion for this in #75.
I also don't think this is a bug per se of the package, but rather a misconfiguration somewhere on your end. Check the discussion for more.
