### ISSUE TITLE
file_get_contents(/var/task/vendor/spatie/browsershot/bin/browser.js): Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by phuclh** [stefanzweifel/sidecar-browsershot#80]
I just upgraded to the latest version and get this error when deploying on Vapor

```
Hook: sidecar:deploy --activate
[Sidecar] Deploying App\Sidecar\Functions\BrowsershotFunction to Lambda as `SC-Project-production-browsershot`.
          ↳ Environment: production
          ↳ Architecture: x86_64
          ↳ Package Type: Zip
          ↳ Runtime: nodejs14.x
          ↳ Function already exists, potentially updating code and configuration.

In BrowsershotFunction.php line 45:
                                                                               
  file_get_contents(/var/task/vendor/spatie/browsershot/bin/browser.js): Failed to open stream: No such file or directory
```

**Comment by stefanzweifel** [comment]
@phuclh both browsershot and sidecar-browsershot are on the latest version? Or can you provide the exact version numbers?

In #78 we've updated the package, as `browser.js` was renamed in the Spatie package in https://github.com/spatie/browsershot/pull/740.

**Comment by phuclh** [comment]
I already found out the issue, you replied so fast, haha.

For some reason my composer locked the package at the old version, I just fixed it and it's working now. Again, thank you for the quick response.
