### ISSUE TITLE
 Function `browsershot` not found in environment `staging` 

### ISSUE THREAD

**Issue by BasemHamad** [stefanzweifel/sidecar-browsershot#89]
wherever I did , always get this issue . 
`
Hammerstone\Sidecar\Exceptions\FunctionNotFoundException: Function `browsershot` not found in environment `staging`. It may exist other environments, you may need to overwrite the environment while deploying to `staging`. See https://hammerstone.dev/sidecar/docs/main/functions/deploying#faking-the-environment for more information. in /var/app/current/vendor/hammerstone/sidecar/src/Exceptions/FunctionNotFoundException.php:23 Stack trace: #0 /var/app/current/vendor/hammerstone/sidecar/src/Manager.php(102): Hammerstone\Sidecar\Exceptions\FunctionNotFoundException::make(Object(Wnx\SidecarBrowsershot\Functions\BrowsershotFunction)) #1

`

and : 

`
[Sidecar] Deploying Wnx\SidecarBrowsershot\Functions\BrowsershotFunction to Lambda as `sc-laravel-staging-browsershot`.
          ↳ Environment: staging
          ↳ Architecture: x86_64
          ↳ Package Type: Zip
          ↳ Runtime: nodejs18.x
          ↳ Function already exists, potentially updating code and configuration.
          ↳ Packaging files for deployment.
          ↳ Package unchanged. Reusing s3://sidecar-space-staging/sidecar/001-a40f37a8be6fb0212ebf7a5703d53b.zip.
          ↳ Function code and configuration are unchanged. Not updating anything.
[Sidecar] Activating function Wnx\SidecarBrowsershot\Functions\BrowsershotFunction.
          ↳ Environment variables not managed by Sidecar. Skipping.
          ↳ Version 2 of sc-laravel-staging-browsershot is already active.

`

from aws lambda : 
![image](https://github.com/stefanzweifel/sidecar-browsershot/assets/42210912/1be6dcd1-552a-4582-b6cb-f23a70b0b5d0)

**Comment by jimhill** [comment]
How did you resolved this @BasemHamad ?
