### ISSUE TITLE
Generated pdf contains [object Object]

### ISSUE THREAD

**Issue by robgaskell** [stefanzweifel/sidecar-browsershot#92]
Since v1.10.0, pdf's generated from a file stored in s3 will generate a pdf that contains only the text:

"[object Object]"

I have been using the following code to see the problem.

```
        $html = BrowsershotLambda::url('https://example.com')->bodyHtml();
        Storage::disk('s3')->put('html/example.html', $html);
        BrowsershotLambda::readHtmlFromS3('html/example.html')->save('example.pdf');
```

**Comment by robgaskell** [comment]
I submitted a PR that fixes the issue for me.
https://github.com/stefanzweifel/sidecar-browsershot/pull/93

**Comment by stefanzweifel** [comment]
Thanks @robgaskell for raising this issue and providing a fix. Will take a closer look once I get the time.
